name: Python package

on: [push]

jobs:
  build:
    name: Build Pipeline
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[lint,test]'
      - name: Lint the code
        run: |
          ruff check lib/
      - name: Typecheck the code
        run: |
          mypy lib/
      - name: Test with pytest
        run: |
          pytest lib -rxXs --cov-report=xml:coverage312.xml --cov lib
