on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Test even2
        run: |
          echo ${{ github.event.pull_request.base.sha }};
          echo ${{ github.event.pull_request.head.sha }};
          echo ${{ github.merge_commit_sha }};
