name: Python package

on: [pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m venv venv
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python lib/setup.py install
      - name: Test with pytest
        run: |
          python -m pytest lib -rxXs --cov-report=xml:coverage312.xml --cov lib
      - name: Comment coverage
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          github_url: ${{ github.event.pull_request.head.repo.url }}
          github_ref: ${{ github.ref }}
          project_name: test_repo
          path: coverage312.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: loicdiridollou/gha-cov-publish@main
